commodity/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = '[commodity]'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    # 无关键字传参
    # url(r"detail/(\d+)", views.CommodityDetail.as_view(), name="commodity_detail"),
    # 关键字传参
    url(r"detail/(?P<id>\d+)", views.CommodityDetail.as_view(), name="commodity_detail"),
    # 上面的url可以改成re_path
    # 另一中传参
    # path("detail/<int: id>/", views.CommodityDetail.as_view(), name="commodity_detail"),

    path("commodity_list/<int:id>/", views.CommodityListView.as_view(), name="commodity_list")
]

operations/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = '[operations]'
urlpatterns = [
    path("flow/", views.FlowListView.as_view(), name="flow"),
    path("add_flow/<int:id>/<int:nums>", views.FlowAddView.as_view(), name="add_flow"),   # 添加购物车
    path("delete_flow", views.FlowDeleteView.as_view(), name="delete_flow"),     # 删除购物车
    path("add_favor", views.FavorAddView.as_view(), name="add_favor"),    # 添加收藏
    path("favor", views.FavorView.as_view(), name="favor"),     # 显示收藏夹
    path("address/<str:commodity_ids>/<str:commodity_nums>", views.AddressView.as_view(), name="address"),  # 跳转到订单的地址界面（并没有真正的存储订单）
    path("add_addr/", views.AddAddressView.as_view(), name="add_addr"),    # 添加地址
    path("add_order/", views.AddOrderView.as_view(), name="add_order"),    # 添加订单
    path("order/", views.OrderView.as_view(), name="order"),     # 订单页面
]

shopping/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shopping import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # 添加验证码url
    url(r'^captcha/', include("captcha.urls")),

    path('user/', include('user.urls', namespace="user")),    # 用户模块
    path('commodity/', include('commodity.urls', namespace="commodity")),    # 商品模块
    path('operations/', include('operations.urls', namespace="operations")),    # 购物车、收藏夹、订单等模块
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)       # 添加配件文件中配置的上传文件路径

user/urls.py
from django.urls import path

from user import views

app_name = '[user]'
urlpatterns = [
    # path("login/", views.user_login, name="user_login"),
    path("login/", views.LoginView.as_view(), name="user_login"),
    # path("register/", views.user_register, name="user_register")
    path("register/", views.RegisterView.as_view(), name="user_register"),
    path("logout/", views.LogoutView.as_view(), name="user_logout"),
    path("profile/", views.ProfileView.as_view(), name="user_profile")
]

commodity/models.py
from django.db import models


# Create your models here.
# 商品类型类
class CommodityType(models.Model):
    name = models.CharField(verbose_name="分类名称", max_length=20)
    level = models.IntegerField(verbose_name="分类级别")
    uper_type = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)

    class Meta():
        verbose_name = "商品分类信息表"

    def __str__(self):
        return self.name


class Commodity(models.Model):
    name = models.CharField(verbose_name="商品名称", max_length=100)
    original_price = models.FloatField(verbose_name="商品原价")
    actual_price = models.FloatField(verbose_name="商品现价")
    freight = models.FloatField(verbose_name="商品运费")
    image = models.ImageField(verbose_name="商品图片", upload_to="uploads/commodity/%Y/%m/%d")
    detail = models.CharField(verbose_name="商品详情", max_length=300)
    sale_nums = models.IntegerField(verbose_name="商品销量")
    all_nums = models.IntegerField(verbose_name="商品库存")
    comments_nums = models.IntegerField(verbose_name="商品评论量")
    favor_nums = models.IntegerField(verbose_name="商品收藏量")
    view_nums = models.IntegerField(verbose_name="商品浏览量")
    created_time = models.DateTimeField(verbose_name="录入时间")
    one_typename = models.ForeignKey("CommodityType", on_delete=models.CASCADE,
                                     null=True, blank=True, related_name="one")
    two_typename = models.ForeignKey("CommodityType", on_delete=models.CASCADE,
                                     null=True, blank=True, related_name="two")
    three_typename = models.ForeignKey("CommodityType", on_delete=models.CASCADE,
                                       null=True, blank=True, related_name="three")

    class Meta():
        verbose_name = "商品信息表"

    def __str__(self):
        return self.name


class CommodityDisplayFiles(models.Model):
    commodity = models.ForeignKey("Commodity", on_delete=models.CASCADE)
    text = models.CharField(verbose_name="说明", max_length=255)
    commodity_file = models.FileField(verbose_name="展示图", upload_to="uploads/commodity/%Y/%m/%d")

    class Meta():
        verbose_name = "商品文件信息表"

    def __str__(self):
        return self.text

commodity/views.py
from pure_pagination import Paginator, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render


# Create your views here.
from django.views.generic.base import View

from commodity.models import Commodity, CommodityType
from operations.models import Cart


def index(request):
    return render(request, "index.html")


class IndexView(View):
    def get(self, request):
        # 菜单栏
        menus = CommodityType.objects.all()
        # 特别推荐
        introducecommoditys = Commodity.objects.all().order_by("-view_nums")
        # 热门商品
        salenumcommoditys = Commodity.objects.all().order_by("-sale_nums")
        # 新品上架
        newcommoditys = Commodity.objects.all().order_by("-created_time")

        # 男女装服饰
        clothes_type = CommodityType.objects.filter(name="服装")[0]
        clothes = Commodity.objects.filter(Q(one_typename=clothes_type.id) |
                                           Q(two_typename=clothes_type.id) |
                                           Q(three_typename=clothes_type.id))

        # 男女装服饰排行榜
        clothes_rank = clothes.order_by("-created_time")

        # 鞋包服饰
        shoes_type = CommodityType.objects.filter(name="鞋包")[0]
        shoes = Commodity.objects.filter(Q(one_typename=shoes_type.id) |
                                         Q(two_typename=shoes_type.id) |
                                         Q(three_typename=shoes_type.id))

        # 鞋包服饰排行榜
        shoes_rank = shoes.order_by("-created_time")

        # 家具
        furniture_type = CommodityType.objects.filter(name="家具")[0]
        furnitures = Commodity.objects.filter(Q(one_typename=furniture_type.id) |
                                              Q(two_typename=furniture_type.id) |
                                              Q(three_typename=furniture_type.id))

        # 家具排行榜
        furnitures_rank = furnitures.order_by("-created_time")

        # 购物车数量

        # cart_nums = Cart.objects.get(user=request.user).numbers
        res_dict = {
            "menus": menus if len(menus) < 8 else menus[:8],
            "introducecommoditys": introducecommoditys if len(introducecommoditys) < 4 else introducecommoditys[:4],
            "salenumcommoditys": salenumcommoditys if len(salenumcommoditys) < 4 else salenumcommoditys[:4],
            "newcommoditys": newcommoditys if len(newcommoditys) < 4 else newcommoditys[:4],
            "clothes": clothes if len(clothes) < 6 else clothes[:6],
            "shoes": shoes if len(shoes) < 6 else shoes[:6],
            "furnitures": furnitures if len(furnitures) < 6 else furnitures[:6],
            "clothes_rank": clothes_rank if len(clothes_rank) < 3 else clothes_rank[:3],
            "shoes_rank": shoes_rank if len(shoes_rank) < 3 else shoes_rank[:3],
            "furnitures_rank": furnitures_rank if len(furnitures_rank) < 3 else furnitures_rank[:3],
            # "cart_nums": cart_nums,
        }

        return render(request, "index.html", res_dict)


class CommodityDetail(View):
    def get(self, request, id):
        commodity = Commodity.objects.get(id=id)
        commodityfiles = commodity.commoditydisplayfiles_set.all()
        commoditys_sales_rank = Commodity.objects.all().order_by("-sale_nums")
        commoditys_views_rank = Commodity.objects.all().order_by("-view_nums")
        return render(request, "commodity.html", {
            "commodity": commodity,
            "commodityfiles": commodityfiles,
            "commoditys_sales_rank": commoditys_sales_rank if len(commoditys_sales_rank) < 4 else commoditys_sales_rank[:4],
            "commoditys_views_rank": commoditys_views_rank if len(commoditys_views_rank) < 4 else commoditys_views_rank[:4]
        })


class CommodityListView(View):
    def get(self, request, id):
        commodity_lists = Commodity.objects.filter(Q(one_typename_id=id) |
                                                   Q(two_typename_id=id) |
                                                   Q(three_typename_id=id))

        # 分页实现
        try:
            page = request.GET.get("page", 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(commodity_lists, 4, request=request)

        commodity_lists = p.page(page)
        return render(request, "commodity_lists.html", {
            "commodity_lists": commodity_lists
        })

templates/address.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>填写地址</title>
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static "css/shop_gouwuche.css" %}" type="text/css" />
<script type="text/javascript" src="{% static "js/jquery.goodnums.js" %}" ></script>
<script type="text/javascript" src="{% static "js/shop_gouwuche.js" %}" ></script>
<style type="text/css">
    .shop_bd_shdz_title{width:1000px; margin-top: 10px; height:50px; line-height: 50px; overflow: hidden; background-color:#F8F8F8;}
    .shop_bd_shdz_title h3{width:120px; text-align: center; height:40px; line-height: 40px; font-size: 14px; font-weight: bold;  background:#FFF; border:1px solid #E8E8E8; border-radius:4px 4px 0 0; float: left;  position: relative; top:10px; left:10px; border-bottom: none;}
    .shop_bd_shdz_title p{float: right;}
    .shop_bd_shdz_title p a{margin:0 8px; color:#555555;}

	.shop_bd_shdz_lists{width:1000px;}
	.shop_bd_shdz_lists ul{width:1000px;}
	.shop_bd_shdz_lists ul li{width:980px; border-radius: 3px; margin:5px 0; padding-left:18px; line-height: 40px; height:40px; border:1px solid #FFE580; background-color:#FFF5CC;}
	.shop_bd_shdz_lists ul li label{color:#626A73; font-weight: bold;}
	.shop_bd_shdz_lists ul li label span{padding:10px;}
	.shop_bd_shdz_lists ul li em{margin:0 4px; color:#626A73;}

	.shop_bd_shdz{width:1000px; margin:10px auto 0;}
	.shop_bd_shdz_new{border:1px solid #ccc; width:998px;}
	.shop_bd_shdz_new div.title{width:990px; padding-left:8px; line-height:35px; height:35px; border-bottom:1px solid #ccc; background-color:#F2F2F2; font-color:#656565; font-weight: bold; font-size:14px;}
	.shdz_new_form{width:980px; padding:9px;}
	.shdz_new_form ul{width:100%;}
	.shdz_new_form ul li{clear:both; width:100%; padding:5px 0; height:25px; line-height: 25px;}
	.shdz_new_form ul li label{float:left;width:100px; text-align: right; padding-right: 10px;}
	.shdz_new_form ul li label span{color:#f00; font-weight: bold; font-size:14px; position: relative; left:-3px; top:2px;}
    </style>

<script type="text/javascript">
	jQuery(function(){
		jQuery("#new_add_shdz_btn").toggle(function(){
			jQuery("#new_add_shdz_contents").show(500);
		},function(){
			jQuery("#new_add_shdz_contents").hide(500);
		});
		jQuery("input[type=submit]").bind("click", function(event){
		    event.preventDefault();
		    var name = jQuery("input[name=name]").val();
		    var addr = jQuery("input[name=addr]").val();
		    var postal = jQuery("input[name=postal]").val();
		    var tel = jQuery("input[name=tel]").val();
            var csrftoken = jQuery("input[name=csrfmiddlewaretoken]").val();

		    var url = "http://127.0.0.1:8000/operations/add_addr/";
		    data = {"name": name, "addr": addr, "postal": postal, "tel": tel, "csrfmiddlewaretoken": csrftoken};
		    jQuery.post(url, data, function(){
		        jQuery("#new_add_shdz_contents").hide(500);
		        window.location.reload()
            });
        });

		jQuery("#add_order_btn").bind("click", function(){
		    var idsE = jQuery("tr input.commodity_id");
		    var ids = [];
            jQuery.each(idsE, function(index, item){
                ids.push(+$(item).val());
            });
            var numsE = jQuery("tr input.good_nums");
            var nums = [];
            jQuery.each(numsE, function(index, item){
                nums.push(+$(item).val());
            });
            var address_id = jQuery("input[type=radio]:checked").val();
            var all_price = jQuery("#good_zongjia").text();
            console.log(address_id, all_price);
            var csrftoken = jQuery("input[name=csrfmiddlewaretoken]").val();
            var url = "http://127.0.0.1:8000/operations/add_order/";
            var data = {
                "ids": ids.toString(),
                "nums": nums.toString(),
                "all_price": all_price,
                "address_id": address_id,
                "csrfmiddlewaretoken": csrftoken};
            $.post(url, data, function (data){
                window.location.href = "http://127.0.0.1:8000/operations/order/"
            });
        });
	});
    var add_c = function(id){
        var commodity_id =  id;
        var csrftoken = $("input[name=csrfmiddlewaretoken]").val();
        if(confirm("确定将该商品收入收藏夹？")){
            $.post("http://127.0.0.1:8000/operations/add_favor", {"commodity_id": commodity_id, "csrfmiddlewaretoken": csrftoken},
            function (data) {
                alert("收藏成功！");
            })
        }
    }
	</script>
{% endblock %}

{% block location %}
<div class="shop_hd_breadcrumb">
    <strong>当前位置：</strong>
    <span>
        <a href="{% url "commodity:index" %}">首页</a>&nbsp;›&nbsp;
        <a href="">我的商城</a>&nbsp;›&nbsp;
        <a href="">我的购物车</a>
    </span>
</div>
<div class="clear"></div>
{% endblock %}

{% block content %}
<!-- 购物车 Body -->
<div class="shop_gwc_bd clearfix">
    <div class="shop_gwc_bd_contents clearfix">

        <!-- 购物流程导航 -->
        <div class="shop_gwc_bd_contents_lc clearfix">
            <ul>
                <li class="step_a">确认购物清单</li>
                <li class="step_b hover_b">确认收货人资料及送货方式</li>
                <li class="step_c">购买完成</li>
            </ul>
        </div>
        <!-- 购物流程导航 End -->
        <div class="clear"></div>
        <!-- 收货地址 title -->
        <div class="shop_bd_shdz_title">
            <h3>收货人地址</h3>
            <p><a href="javasrcipt:void(0);" id="new_add_shdz_btn">新增收货地址</a><a href="javascript:void(0);">管理收货地址</a></p>
        </div>
        <div class="clear"></div>
        <!-- 收货人地址 Title End -->
        <div class="shop_bd_shdz clearfix">
            <div class="shop_bd_shdz_lists clearfix">
                <ul>
                    {% for address in addresss %}
                    <li>
                        <label>寄送至：<span><input type="radio" name="address" value="{{ address.id }}"/></span></label>
                        <em>{{ address.addr }}</em><em>{{ address.name }}(收)</em><em>{{ address.tel }}</em>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <!-- 新增收货地址 -->
            <div id="new_add_shdz_contents" style="display:none;" class="shop_bd_shdz_new clearfix">
                <div class="title">新增收货地址</div>
                <div class="shdz_new_form">
                    <form>
                        {% csrf_token %}
                        <ul>
                            <li><label for=""><span>*</span>收货人姓名：</label><input type="text" name="name" class="name" /></li>
                            <li><label for=""><span>*</span>详细地址：</label><input type="text" name="addr" class="xiangxi" /></li>
                            <li><label for=""><span></span>邮政编码：</label><input type="text" name="postal" class="youbian" /></li>
                            <li><label for=""><span>*</span>手机号：</label><input type="text" name="tel" class="shouji" /></li>
                            <li><label for="">&nbsp;</label><input type="submit" value="增加收货地址" /></li>
                        </ul>
                    </form>
                </div>
            </div>
            <!-- 新增收货地址 End -->
        </div>
        <div class="clear"></div>
        <!-- 购物车列表 -->
        <div class="shop_bd_shdz_title">
            <h3>确认购物清单</h3>
        </div>
        <div class="clear"></div>
        <table>
            <thead>
                <tr>
                    <th colspan="2"><span>商品</span></th>
                    <th><span>单价(元)</span></th>
                    <th><span>数量</span></th>
                    <th><span>小计</span></th>
                    <th><span>操作</span></th>
                </tr>
            </thead>
            <tbody>
                {% for commodity in commoditys %}
                <tr id="commodity{{ commodity.id }}">
                    <td class="gwc_list_pic"><a href=""><img src="{{ commodity.image.url }}" /></a></td>
                    <td class="gwc_list_title"><a href="">{{ commodity.name }} </a></td>
                    <td class="gwc_list_danjia"><span>￥<strong id="danjia_{{commodity.id}}">{{ commodity.actual_price }}</strong></span></td>
                    <td class="gwc_list_shuliang">
                        <span>
                            <a class="good_num_jian this_good_nums" did="danjia_{{commodity.id}}" xid="xiaoji_{{commodity.id}}" ty="-" valId="goods_{{commodity.id}}" href="javascript:void(0);">-</a>
                            <input type="hidden" value="{{ commodity.id }}" class="commodity_id">
                            <input type="text" value="{{ commodity.nums }}" id="goods_{{commodity.id}}" class="good_nums" />
                            <a href="javascript:void(0);" did="danjia_{{commodity.id}}" xid="xiaoji_{{commodity.id}}" ty="+" class="good_num_jia this_good_nums" valId="goods_{{commodity.id}}">+</a>
                        </span>
                    </td>
                    <td class="gwc_list_xiaoji"><span>￥<strong id="xiaoji_{{commodity.id}}" class="good_xiaojis">{% widthratio commodity.actual_price 1 commodity.nums %}</strong></span></td>
                    <td class="gwc_list_caozuo">
                        <a href="javascript:void(0);" onclick="add_c({{ commodity.id }})">收藏</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">
                        <div class="gwc_foot_zongjia">商品总价(不含运费)<span>￥<strong id="good_zongjia">{{ all_price }}</strong></span></div>
                        <div class="clear"></div>
                        <div class="gwc_foot_links">
                            <a href="{% url "operations:flow" %}" class="go">返回上一步</a>
                            <a href="javascript:void(0);" class="op" id="add_order_btn">确认收货地址</a>
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>
        <!-- 购物车列表 End -->

    </div>
</div>
<!-- 购物车 Body End -->
{% endblock %}

templates/base.html
{% load static %}
{% load extraTag %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    {% block title %}{% endblock %}
	<link rel="stylesheet" href="{% static "css/base.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "css/shop_common.css" %}" type="text/css" />
	<link rel="stylesheet" href="{% static "css/shop_header.css" %}" type="text/css" />
    <script type="text/javascript" src="{% static "js/jquery.js" %}" ></script>
    <script type="text/javascript" src="{% static "js/topNav.js" %}" ></script>
    {% block head %}

    {% endblock %}
</head>
<body>
	<!-- Header  -wll-2013/03/24 -->
	<div class="shop_hd">
		<!-- Header TopNav -->
		<div class="shop_hd_topNav">
			<div class="shop_hd_topNav_all">
				<!-- Header TopNav Left -->
				<div class="shop_hd_topNav_all_left">
					<p>您好，欢迎来到<b><a href="/">小胡商城</a></b>[<a href="">登录</a>][<a href="">注册</a>]</p>
				</div>
				<!-- Header TopNav Left End -->

				<!-- Header TopNav Right -->
				<div class="shop_hd_topNav_all_right">
					<ul class="topNav_quick_menu">

						<li>
							<div class="topNav_menu">
								<a href="#" class="topNavHover">我的商城<i></i></a>
								<div class="topNav_menu_bd" style="display:none;" >
						            <ul>
						              <li><a title="已买到的商品" target="_top" href="{% url "operations:order" %}">已买到的商品</a></li>
						              <li><a title="个人主页" target="_top" href="{% url "user:user_profile" %}">个人主页</a></li>
						              <li><a title="我的好友" target="_top" href="#">我的好友</a></li>
						            </ul>
						        </div>
							</div>
						</li>
                        <li>
							<div class="topNav_menu">
								<a href="#" class="topNavHover">卖家中心<i></i></a>
								<div class="topNav_menu_bd" style="display:none;">
						            <ul>
						              <li><a title="已售出的商品" target="_top" href="#">已售出的商品</a></li>
						              <li><a title="销售中的商品" target="_top" href="#">销售中的商品</a></li>
						            </ul>
						        </div>
							</div>
						</li>
						<li>
							<div class="topNav_menu">
								<a href="#" class="topNavHover">购物车<b>{{ cart_nums }}</b>种商品<i></i></a>
								<div class="topNav_menu_bd" style="display:none;">
									<!--
						            <ul>
						              <li><a title="已售出的商品" target="_top" href="#">已售出的商品</a></li>
						              <li><a title="销售中的商品" target="_top" href="#">销售中的商品</a></li>
						            </ul>
						        	-->
						            <p>还没有商品，赶快去挑选！</p>
						        </div>
							</div>
						</li>
						<li>
							<div class="topNav_menu">
								<a href="#" class="topNavHover">我的收藏<i></i></a>
								<div class="topNav_menu_bd" style="display:none;">
						            <ul>
						              <li><a title="收藏的商品" target="_top" href="{% url "operations:favor" %}">收藏的商品</a></li>
						              <li><a title="收藏的店铺" target="_top" href="#">收藏的店铺</a></li>
						            </ul>
						        </div>
							</div>
						</li>
						<li>
							<div class="topNav_menu">
								<a href="{% url "user:user_logout" %}">注&emsp;&emsp;销</a>
							</div>
						</li>

					</ul>
				</div>
				<!-- Header TopNav Right End -->
			</div>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
		<!-- Header TopNav End -->

		<!-- TopHeader Center -->
		<div class="shop_hd_header">
			<div class="shop_hd_header_logo">
                <h1 class="logo">
                    <a href="/" style="text-decoration: none; font-size: 26px; color: #FE8502;">微商城</a><span>小胡</span>
                </h1>
            </div>
			<div class="shop_hd_header_search">
                <ul class="shop_hd_header_search_tab">
			        <li id="search" class="current">商品</li>
			        <li id="shop_search">店铺</li>
			    </ul>
                <div class="clear"></div>
			    <div class="search_form">
			    	<form method="post" action="">
			    		<div class="search_formstyle">
			    			<input type="text" class="search_form_text" name="search_content" value="搜索其实很简单！" />
			    			<input type="submit" class="search_form_sub" name="secrch_submit" value="" title="搜索" />
			    		</div>
			    	</form>
			    </div>
                <div class="clear"></div>
			    <div class="search_tag">
			    	<a href="">李宁</a>
			    	<a href="">耐克</a>
			    	<a href="">Kappa</a>
			    	<a href="">双肩包</a>
			    	<a href="">手提包</a>
			    </div>

			</div>
		</div>
		<div class="clear"></div>
		<!-- TopHeader Center End -->

		<!-- Header Menu -->
		<div class="shop_hd_menu">
			<!-- 所有商品菜单 -->
            {% block nav %}
            <div id="shop_hd_menu_all_category" class="shop_hd_menu_all_category"><!-- 首页去掉 id="shop_hd_menu_all_category" 加上clsss shop_hd_menu_hover -->
            {% endblock %}
				<div class="shop_hd_menu_all_category_title"><h2 title="所有商品分类"><a href="javascript:void(0);">所有商品分类</a></h2><i></i></div>
				<div id="shop_hd_menu_all_category_hd" class="shop_hd_menu_all_category_hd">
					<ul class="shop_hd_menu_all_category_hd_menu clearfix">
						<!-- 单个菜单项 -->
                        {% TypeTag as ones %}
                        {% for one in ones %}
                         <li id="cat_1" class="">
							<h3><a href="{% url "commodity:commodity_list" one.id %}" title="男女服装">{{ one.name }}</a></h3>
							<div id="cat_1_menu" class="cat_menu clearfix" style="">
                                {% for two in one.two %}
                                <dl class="clearfix">
									<dt><a href="{% url "commodity:commodity_list" two.id %}">{{ two.name }}</a></dt>
									<dd>
                                        {% for three in two.three %}
                                        <a href="{% url "commodity:commodity_list" two.id %}">{{ three.name }}</a>
                                        {% endfor %}
									</dd>
								</dl>
                                {% endfor %}
							</div>
						</li>
                        {% endfor %}
						<!-- 单个菜单项 End -->
                        <li class="more"><a href="">查看更多分类</a></li>
					</ul>
				</div>
			{% block endnav %}
			</div>
			{% endblock %}

			<!-- 所有商品菜单 END -->

			<!-- 普通导航菜单 -->
			<ul class="shop_hd_menu_nav">
				<li class="current_link"><a href="{% url "commodity:index" %}"><span>首页</span></a></li>
				<li class="link"><a href="#"><span>商城</span></a></li>
				<li class="link"><a href="#"><span>品牌</span></a></li>
				<li class="link"><a href="#"><span>优惠卷</span></a></li>
				<li class="link"><a href="#"><span>积分中心</span></a></li>
				<li class="link"><a href="#"><span>运动专场</span></a></li>
				<li class="link"><a href="#"><span>微商城</span></a></li>
			</ul>
			<!-- 普通导航菜单 End -->
		</div>
		<!-- Header Menu End -->

	</div>
	<div class="clear"></div>

	<!-- 面包屑 注意首页没有 -->
    {% block location %}

    {% endblock %}

	<!-- 面包屑 End -->

	<!-- Header End -->
	
	<!-- Goods Body -->
    {% block content %}

    {% endblock %}
	<!-- Goods Body End -->

	<!-- Footer - wll - 2013/3/24 -->
	<div class="clear"></div>
	<div class="shop_footer">
            <div class="shop_footer_link">
                <p>
                    <a href="">首页</a>|
                    <a href="">招聘英才</a>|
                    <a href="">广告合作</a>|
                    <a href="">关于briup</a>|
                    <a href="">关于我们</a>
                </p>
            </div>
            <div class="shop_footer_copy">
                <p>Copyright 2004-2013 itcast Inc.,All rights reserved.</p>
            </div>
        </div>
	<!-- Footer End -->

</body>
</html>